server:
  port: 8083
spring:
  application:
    name: le-blog
  datasource:
    url: jdbc:mysql://localhost:3306/le-project?characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: root
