server:
  port: 8083
spring:
  application:
    name: le-blog
  datasource:
    url: jdbc:mysql://localhost:3306/le-project?characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: root
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.example.leblog.entity
