server:
  port: 8001
spring:
  application:
    name: le-user
  datasource:
    url: jdbc:mysql://localhost:3306/le-project?characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
jwt:
  expire-minute: 10
  token-name: le-token
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
